apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/sidhuni/apps-repo.git
    targetRevision: main
    ref: values
  - repoURL: https://chartmuseum.github.io/charts
    targetRevision: 3.10.1
    chart: chartmuseum
    helm:
      valueFiles:
      - $values/chartmuseum/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true 
      allowEmpty: false
    syncOptions:
    - Validate=false