apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: http://chartmuseum.chartmuseum.svc.cluster.local:8080
      chart: common-app-chart
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $valuesrepo/app3/values.yaml

    - repoURL: https://github.com/sidhuni/helm-values-repo.git
      targetRevision: main
      ref: valuesrepo

  destination:
    server: https://kubernetes.default.svc
    namespace: app3

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

