apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/descheduler
    chart: descheduler
    targetRevision: 0.35.0
    helm:
      valueFiles:
      - $values/descheduler/values.yaml

  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Validate=false
