
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-kibana
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://helm.elastic.co'
    targetRevision: 0.17.0
    chart: eck-kibana
    helm:
      valueFiles:
      - $values/eck-kibana/values.yaml
  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: eck-operator
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - Validate=false
  automated:
      prune: true
      selfHeal: true

