apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://helm.elastic.co'
    targetRevision: 0.17.0
    chart: eck-elasticsearch
    helm:
      valueFiles:
      - $values/eck-elasticsearch/values.yaml
  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: eck-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true