apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-elasticsearch
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/sidhuni/tools-app.git'
    targetRevision: main
    path: eck-elasticsearch   # folder containing elasticsearch.yaml (CRD manifest)

  destination:
    server: "https://kubernetes.default.svc"
    namespace: eck-elasticsearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /metadata/creationTimestamp
        - /metadata/uid
        - /metadata/resourceVersion
        - /metadata/managedFields
        - /data
