apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 8.4.2
      helm:
        valueFiles:
          - $values/grafana/values.yaml

    - repoURL: https://github.com/sidhuni/apps-repo.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana    # ← ArgoCD must create this

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true   # ← REQUIRED
      - Validate=false
