apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.karpenter.sh/
    chart: karpenter
    targetRevision: 0.16.3
    helm:
      valueFiles:
      - $values/karpenter/values.yaml

  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true   
      - Validate=false