
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiill
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://helm.elastic.co'
    targetRevision: 8.5.1
    chart: kibana
    helm:
      valueFiles:
      - $values/ki/values.yaml
  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - Validate=false
  automated:
      prune: true
      selfHeal: true

