apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 8.5.1
    chart: kibana
    helm:
      valueFiles:
        - $values/kibana/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kibana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
