apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-pro
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.3.2
    helm:
      valueFiles:
      - $values/kube-pro/values.yaml

  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-pro

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Validate=false
