apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://avistotelecom.github.io/charts/
    chart: wazuh-agent
    targetRevision: 4.12.0
    helm:
      valueFiles:
      - $values/wazuh/values.yaml

  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Validate=false