
serviceAccount:
  create: true
  name: ""
  annotations: {}

replicas: 1


settings:
  clusterName: "local-cluster"

controller:
  resources:
   requests:
     cpu: 250m
     memory: 512Mi
   limits: 
     cpu: 500m
     memory: 512Mi

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule