apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *"  # Once a minute for testing
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          # This ensures the pod can write to the PVC on Rancher Desktop
          serviceAccountName: "postgresql"
          volumes:
            - name: aws-cli-bin
              emptyDir: {}
          initContainers:
          - name: install-aws
            image: amazon/aws-cli:latest
            command: ["cp", "-r", "/usr/local/aws-cli", "/target/"]
            volumeMounts:
            - name: aws-cli-bin
              mountPath: /target
          containers:
            - name: backup
              image: registry-1.docker.io/bitnami/postgresql:latest
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets
                      key: user_password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
                - name: aws-cli-bin
                  mountPath: /usr/local/aws-cli
              command:
              - /bin/sh
              - -c
              - |
                set -e
                # Manually link the borrowed AWS CLI
                export PATH=$PATH:/usr/local/aws-cli/v2/current/bin
                
                TIMESTAMP=$(date +%Y-%m-%d)
                DB_LIST=$(psql -h postgresql -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                for DB in $DB_LIST; do
                  echo "Backing up: $DB"
                  pg_dump -h postgresql -U "$PGUSER" "$DB" | gzip | aws s3 cp - s3://$BUCKET/$TIMESTAMP/$DB.sql.gz
                done
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
