apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: postgres:16
              env:
                - name: PGUSER
                  value: admin
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-backup-creds
                      key: password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  echo "Automatic Backup Started at $(date -u)"

                  DATE=$(date +%Y-%m-%d)
                  BACKUP_DIR="/backups/$DATE"
                  mkdir -p "$BACKUP_DIR"

                  echo "Testing connection..."
                  psql -h postgresql -d chms -c "SELECT 1;" >/dev/null

                  echo "Fetching database list..."
                  DB_LIST=$(psql -h postgresql -At \
                    -c "SELECT datname FROM pg_database WHERE datistemplate = false;")

                  for DB in $DB_LIST; do
                    echo "Backing up database: $DB"
                    pg_dump -h postgresql "$DB" | gzip > "$BACKUP_DIR/$DB.sql.gz"
                    echo "Done: $DB ($(du -sh "$BACKUP_DIR/$DB.sql.gz" | cut -f1))"
                  done

                  echo "Cleaning backups older than 5 days..."
                  cd /backups && ls -dt */ | tail -n +6 | xargs -r rm -rf

                  echo "✅ Backup completed successfully"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
