apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-s3-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" # Every minute for local testing
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup-worker
            image: public.ecr.aws/docker/library/ubuntu:24.04
            env:
              - name: PGUSER
                value: "admin"
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secrets
                    key: user_password
              - name: PGHOST
                value: "postgresql" # Your DB Service name
              - name: BUCKET
                value: "postgresqlb-backup"
            command:
              - /bin/sh
              - -c
              - |
                set -e
                
                # 1. Update and install basic tools
                apt-get update && apt-get install -y curl ca-certificates gnupg unzip gzip
                
                # 2. CREATE THE MISSING DIRECTORY (This fixes your error)
                mkdir -p /usr/share/postgresql-common/pgdg/
                
                # 3. Add Postgres 18 Repo
                curl -fsSLk https://www.postgresql.org | gpg --dearmor -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg
                echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg] http://apt.postgresql.org noble-pgdg main" > /etc/apt/sources.list.d/pgdg.list

                # 4. Install Postgres Client 18
                apt-get update && apt-get install -y postgresql-client-18
                
                # 5. Install AWS CLI v2 for ARM64 (aarch64)
                echo "Downloading AWS CLI for ARM64..."
                curl -Lk "https://awscli.amazonaws.com" -o "awscliv2.zip"
                unzip -q awscliv2.zip && ./aws/install
                
                # 6. Verification Check
                echo "--- Tool Versions ---"
                aws --version
                pg_dump --version

                # 7. Backup Logic
                TIMESTAMP=$(date +%Y-%m-%d)
                DB_LIST=$(psql -h $PGHOST -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                for DB in $DB_LIST; do
                  echo "Backing up: $DB"
                  pg_dump -h $PGHOST -U "$PGUSER" "$DB" | gzip | aws s3 cp - s3://$BUCKET/$TIMESTAMP/$DB.sql.gz
                  echo "✅ Uploaded $DB"
                done
