apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "0 2 * * *"  # Runs every day at 2:00 AM
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: registry-1.docker.io/bitnami/postgresql:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1001
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets
                      key: user_password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  DATE=$(date +%Y-%m-%d_%H-%M)
                  BACKUP_DIR="/backups/$DATE"
                  mkdir -p "$BACKUP_DIR"

                  echo "--- Starting Global Backup: $DATE ---"
                  
                  # This finds ALL databases you created (chms, inventory, orders, etc.)
                  DB_LIST=$(psql -h postgresql -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                  for DB in $DB_LIST; do
                    FILE_PATH="$BACKUP_DIR/$DB.sql.gz"
                    echo "Backing up: $DB"
                    pg_dump -h postgresql -U "$PGUSER" "$DB" | gzip > "$FILE_PATH"
                    SIZE=$(du -sh "$FILE_PATH" | cut -f1)
                    echo "✅ Saved $DB.sql.gz ($SIZE)"
                  done

                  # Keep only the last 5 backup events (5 folders)
                  echo "Rotating old backups..."
                  cd /backups && ls -dt 20* | tail -n +6 | xargs -r rm -rf
                  
                  echo "--- Global Backup Complete ---"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
