apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *"  # Once a minute for testing
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          # This ensures the pod can write to the PVC on Rancher Desktop
          securityContext:
            fsGroup: 1001
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: registry-1.docker.io/bitnami/postgresql:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1001
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets
                      key: user_password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  # 1. Create directory for current backup
                  DATE=$(date +%Y-%m-%d_%H-%M-%S)
                  BACKUP_DIR="/backups/$DATE"
                  mkdir -p "$BACKUP_DIR"

                  echo "--- Backup Started: $(date) ---"
                  
                  # 2. Get database list
                  DB_LIST=$(psql -h postgresql -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                  for DB in $DB_LIST; do
                    FILE_PATH="$BACKUP_DIR/$DB.sql.gz"
                    echo "Backing up: $DB ..."
                    pg_dump -h postgresql -U "$PGUSER" "$DB" | gzip > "$FILE_PATH"
                    SIZE=$(du -sh "$FILE_PATH" | cut -f1)
                    echo "✅ Done: $DB.sql.gz (Size: $SIZE)"
                  done

                  # 3. ROLLING DELETE: Keep only the 5 most recent folders
                  # This lists directories by time (newest first), skips the first 5, and deletes the rest
                  echo "Checking for old backups (Keeping latest 5)..."
                  cd /backups
                  ls -dt 20* | tail -n +6 | xargs -r rm -rf
                  
                  echo "--- All backups finished successfully ---"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
