apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
          restartPolicy: OnFailure

          # ONLY ONE VOLUMES LIST
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
            - name: aws-tools 
              emptyDir: {}
            # Keep your secret CSI volume if you are using it
            - name: postgresql-secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "postgresql-secrets"

          initContainers:
          - name: install-aws
            image: amazon/aws-cli:latest
            command: ["/bin/sh", "-c", "cp -pr /usr/local/aws-cli /target/"]
            volumeMounts:
            - name: aws-tools
              mountPath: /target

          containers:
            - name: backup
              image: registry-1.docker.io/bitnami/postgresql:latest
              securityContext:
                runAsUser: 1001
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets
                      key: user_password
                - name: BUCKET
                  value: "postgresqlb-backup"
                - name: PGHOST
                  value: "postgresql"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
                - name: aws-tools   # This name must match the name in the volumes list
                  mountPath: /opt/aws-tools
                - name: postgresql-secrets
                  mountPath: "/mnt/postgresql-secrets"
                  readOnly: true
              command:
              - /bin/sh
              - -c
              - |
                set -e
                
                # Point to the dist folder where the 'aws' executable lives
                export PATH=$PATH:/opt/aws-tools/aws-cli/v2/current/dist
                
                # Check tools (This will show up in your logs)
                echo "--- Environment Check ---"
                aws --version
                
                TIMESTAMP=$(date +%Y-%m-%d)
                echo "--- Starting S3 Backup for $TIMESTAMP ---"

                # 1. Get DB List
                DB_LIST=$(psql -h $PGHOST -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                for DB in $DB_LIST; do
                  echo "Backing up: $DB"
                  # 2. pg_dump | gzip | aws s3
                  pg_dump -h $PGHOST -U "$PGUSER" "$DB" | gzip | aws s3 cp - s3://$BUCKET/$TIMESTAMP/$DB.sql.gz
                  echo "✅ Uploaded $DB.sql.gz to S3"
                done
                
                echo "--- All backups finished successfully ---"
