apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  # This runs every 5 minutes automatically
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            # Use this specific tag to avoid the ImagePullBackOff error
            image: docker.io/bitnamilegacy/postgresql:16
            imagePullPolicy: Always
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: postgres-password
            command:
              - /bin/sh
              - -c
              - |
                echo "Automatic Backup Started at $(date)"
                # -h postgresql matches your fullnameOverride
                pg_dump -h postgresql -U admin chms > /tmp/backup.sql
                echo "Backup Success. Size: $(du -sh /tmp/backup.sql)"
          restartPolicy: OnFailure
