apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-s3-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" # Every minute for local testing
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-worker
            image: ubuntu:24.04 # Stable LTS version
            env:
              - name: PGUSER
                value: "admin"
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secrets
                    key: user_password
              - name: PGHOST
                value: "postgresql" # Your DB Service name
              - name: BUCKET
                value: "postgresqlb-backup"
            command:
              - /bin/sh
              - -c
              - |
                set -e
                # 1. Update and install tools (This is why we use Ubuntu!)
                apt-get update && apt-get install -y curl unzip postgresql-client gzip
                
                # 2. Install AWS CLI v2
                curl "https://awscli.amazonaws.com" -o "awscliv2.zip"
                unzip -q awscliv2.zip && ./aws/install
                
                # 3. Perform backup and upload to S3
                TIMESTAMP=$(date +%Y-%m-%d)
                # Get the list of databases from the Bitnami pod via the network
                DB_LIST=$(psql -h $PGHOST -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                for DB in $DB_LIST; do
                  echo "Backing up: $DB"
                  pg_dump -h $PGHOST -U "$PGUSER" "$DB" | gzip | aws s3 cp - s3://$BUCKET/$TIMESTAMP/$DB.sql.gz
                done
          restartPolicy: OnFailure
