apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" # Runs every 5 mins for testing
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: bitnami/postgresql:16
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: postgres-password
            command:
              - /bin/sh
              - -c
              - |
                echo "Starting backup..."
                pg_dump -h postgresql -U admin chms > /backups/local-test.sql
                echo "Backup finished. Size: $(du -sh /backups/local-test.sql)"
                sleep 300 # Keeps pod alive for 5 mins so you can inspect it
            volumeMounts:
              - name: temp-storage
                mountPath: /backups
          volumes:
            - name: temp-storage
              emptyDir: {}
          restartPolicy: OnFailure
