apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgresql-secrets
spec:
  provider: local
  parameters:
    # Directory path where secrets are stored locally
    # You can store your secret files under /tmp/secrets or any path accessible by your cluster
    files: |
      - fileName: postgres_password
        filePath: /tmp/secrets/postgres_password
      - fileName: user_password
        filePath: /tmp/secrets/user_password

  secretObjects:
    - data:
        - key: postgres_password
          objectName: postgres_password
        - key: user_password
          objectName: user_password
      secretName: postgresql-secrets
      type: Opaque
