apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sidhuni/my-checksum-helmchart.git
    path: common-app-chart
    targetRevision: main
    helm:
      valueFiles:
        - $valuesrepo/app1/values.yaml
  sources:
    - repoURL: https://github.com/sidhuni/my-checksum-helmchart.git
      path: common-app-chart
    - repoURL: https://github.com/sidhuni/helm-values-repo.git
      targetRevision: main
      ref: valuesrepo
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
