pilot:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  autoscaleBehavior: {}
  replicaCount: 1
  rollingMaxSurge: 100%
  rollingMaxUnavailable: 25%
  hub: "383478357652.dkr.ecr.ap-south-1.amazonaws.com"
  tag: "sre-common:istio-pilot-1.25.3"
  variant: ""
  image: ""
  traceSampling: 1.0
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
  seccompProfile: {}
  cni:
    enabled: false
    provider: default
  extraContainerArgs: []
  env: {}
  taint:
    enabled: false
    namespace: ""
  affinity: {}
  tolerations: []
  cpu:
    targetAverageUtilization: 80
  memory: {}
  volumeMounts: []
  volumes: []
  nodeSelector: {}
  podAnnotations: {}
  serviceAnnotations: {}
  serviceAccountAnnotations: {}
  topologySpreadConstraints: []
  jwksResolverExtraRootCA: ""
  configSource:
    subscribedResources: []
  keepaliveMaxServerConnectionAge: 30m
  deploymentLabels: {}
  configMap: true
  podLabels: {}
  ipFamilyPolicy: ""
  ipFamilies: []
sidecarInjectorWebhook:
  neverInjectSelector: []
  alwaysInjectSelector: []
  injectedAnnotations: {}
  enableNamespacesByDefault: false
  reinvocationPolicy: Never
  rewriteAppHTTPProbe: true
  templates: {}
  defaultTemplates: []
istiodRemote:
  injectionURL: ""
  injectionPath: "/inject"
  injectionCABundle: ""
telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true
    stackdriver:
      enabled: false
revision: ""
revisionTags: []
ownerName: ""
meshConfig:
  enablePrometheusMerge: true
experimental:
  stableValidationPolicy: false
global:
  istioNamespace: istio-system
  certSigners: []
  defaultPodDisruptionBudget:
    enabled: true
  defaultResources:
    requests:
      cpu: 10m
      memory: 128Mi
  hub: "383478357652.dkr.ecr.ap-south-1.amazonaws.com"
  tag: "sre-common:istio-proxy-1.25.3" 
  variant: ""
  imagePullPolicy: ""
  imagePullSecrets: 
    - ecr-pull-secret
  istiod:
    enableAnalysis: false
  logAsJson: false
  logging:
    level: "default:info"
  omitSidecarInjectorConfigMap: false
  operatorManageWebhooks: false
  priorityClassName: ""
  proxy:
    image: ""
    autoInject: enabled
    clusterDomain: "cluster.local"
    componentLogLevel: "misc:error"
    enableCoreDump: false
    excludeInboundPorts: ""
    includeInboundPorts: "*"
    includeIPRanges: "*"
    excludeIPRanges: ""
    includeOutboundPorts: ""
    excludeOutboundPorts: ""
    logLevel: warning
    privileged: false
    readinessFailureThreshold: 4
    readinessInitialDelaySeconds: 0
    readinessPeriodSeconds: 15
    startupProbe:
      enabled: true
      failureThreshold: 600 
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
    statusPort: 15020
    tracer: "none"
  proxy_init:
    image: ""               
    forceApplyIptables: false
    

  caAddress: ""
  externalIstiod: false
  configCluster: false
  configValidation: true
  meshID: ""
  meshNetworks: {}
  mountMtlsCerts: false
  multiCluster:
    enabled: false
    clusterName: ""
  network: ""
  pilotCertProvider: istiod
  sds:
    token:
      aud: istio-ca
  sts:
    servicePort: 0
  caName: ""
  autoscalingv2API: true
base:
  enableIstioConfigCRDs: true
istio_cni:
  chained: true
  provider: default
